/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangRouteRouteImport } from './routes/$lang/route'
import { Route as LangIndexRouteImport } from './routes/$lang/index'
import { Route as LangAdminRouteImport } from './routes/$lang/admin'
import { Route as LangCategoriesRouteImport } from './routes/$lang/categories'
import { Route as LangLoginRouteImport } from './routes/$lang/login'
import { Route as LangRankRouteImport } from './routes/$lang/rank'
import { Route as LangRegisterRouteImport } from './routes/$lang/register'
import { Route as LangSavedRouteImport } from './routes/$lang/saved'
import { Route as LangSearchRouteImport } from './routes/$lang/search'
import { Route as LangSubmitRouteImport } from './routes/$lang/submit'
import { Route as LangCSlugRouteImport } from './routes/$lang/c/$slug'
import { Route as LangPIdRouteImport } from './routes/$lang/p/$id'
import { Route as LangPagePageRouteImport } from './routes/$lang/page/$page'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangRouteRoute = LangRouteRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangAdminRoute = LangAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangCategoriesRoute = LangCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangLoginRoute = LangLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangRankRoute = LangRankRouteImport.update({
  id: '/rank',
  path: '/rank',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangRegisterRoute = LangRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangSavedRoute = LangSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangSearchRoute = LangSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangSubmitRoute = LangSubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangCSlugRoute = LangCSlugRouteImport.update({
  id: '/c/$slug',
  path: '/c/$slug',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangPIdRoute = LangPIdRouteImport.update({
  id: '/p/$id',
  path: '/p/$id',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangPagePageRoute = LangPagePageRouteImport.update({
  id: '/page/$page',
  path: '/page/$page',
  getParentRoute: () => LangRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteRouteWithChildren
  '/$lang/admin': typeof LangAdminRoute
  '/$lang/categories': typeof LangCategoriesRoute
  '/$lang/login': typeof LangLoginRoute
  '/$lang/rank': typeof LangRankRoute
  '/$lang/register': typeof LangRegisterRoute
  '/$lang/saved': typeof LangSavedRoute
  '/$lang/search': typeof LangSearchRoute
  '/$lang/submit': typeof LangSubmitRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/c/$slug': typeof LangCSlugRoute
  '/$lang/p/$id': typeof LangPIdRoute
  '/$lang/page/$page': typeof LangPagePageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$lang/admin': typeof LangAdminRoute
  '/$lang/categories': typeof LangCategoriesRoute
  '/$lang/login': typeof LangLoginRoute
  '/$lang/rank': typeof LangRankRoute
  '/$lang/register': typeof LangRegisterRoute
  '/$lang/saved': typeof LangSavedRoute
  '/$lang/search': typeof LangSearchRoute
  '/$lang/submit': typeof LangSubmitRoute
  '/$lang': typeof LangIndexRoute
  '/$lang/c/$slug': typeof LangCSlugRoute
  '/$lang/p/$id': typeof LangPIdRoute
  '/$lang/page/$page': typeof LangPagePageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteRouteWithChildren
  '/$lang/admin': typeof LangAdminRoute
  '/$lang/categories': typeof LangCategoriesRoute
  '/$lang/login': typeof LangLoginRoute
  '/$lang/rank': typeof LangRankRoute
  '/$lang/register': typeof LangRegisterRoute
  '/$lang/saved': typeof LangSavedRoute
  '/$lang/search': typeof LangSearchRoute
  '/$lang/submit': typeof LangSubmitRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/c/$slug': typeof LangCSlugRoute
  '/$lang/p/$id': typeof LangPIdRoute
  '/$lang/page/$page': typeof LangPagePageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/$lang/admin'
    | '/$lang/categories'
    | '/$lang/login'
    | '/$lang/rank'
    | '/$lang/register'
    | '/$lang/saved'
    | '/$lang/search'
    | '/$lang/submit'
    | '/$lang/'
    | '/$lang/c/$slug'
    | '/$lang/p/$id'
    | '/$lang/page/$page'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$lang/admin'
    | '/$lang/categories'
    | '/$lang/login'
    | '/$lang/rank'
    | '/$lang/register'
    | '/$lang/saved'
    | '/$lang/search'
    | '/$lang/submit'
    | '/$lang'
    | '/$lang/c/$slug'
    | '/$lang/p/$id'
    | '/$lang/page/$page'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/$lang/admin'
    | '/$lang/categories'
    | '/$lang/login'
    | '/$lang/rank'
    | '/$lang/register'
    | '/$lang/saved'
    | '/$lang/search'
    | '/$lang/submit'
    | '/$lang/'
    | '/$lang/c/$slug'
    | '/$lang/p/$id'
    | '/$lang/page/$page'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRouteRoute: typeof LangRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/admin': {
      id: '/$lang/admin'
      path: '/admin'
      fullPath: '/$lang/admin'
      preLoaderRoute: typeof LangAdminRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/categories': {
      id: '/$lang/categories'
      path: '/categories'
      fullPath: '/$lang/categories'
      preLoaderRoute: typeof LangCategoriesRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/login': {
      id: '/$lang/login'
      path: '/login'
      fullPath: '/$lang/login'
      preLoaderRoute: typeof LangLoginRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/rank': {
      id: '/$lang/rank'
      path: '/rank'
      fullPath: '/$lang/rank'
      preLoaderRoute: typeof LangRankRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/register': {
      id: '/$lang/register'
      path: '/register'
      fullPath: '/$lang/register'
      preLoaderRoute: typeof LangRegisterRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/saved': {
      id: '/$lang/saved'
      path: '/saved'
      fullPath: '/$lang/saved'
      preLoaderRoute: typeof LangSavedRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/search': {
      id: '/$lang/search'
      path: '/search'
      fullPath: '/$lang/search'
      preLoaderRoute: typeof LangSearchRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/submit': {
      id: '/$lang/submit'
      path: '/submit'
      fullPath: '/$lang/submit'
      preLoaderRoute: typeof LangSubmitRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/c/$slug': {
      id: '/$lang/c/$slug'
      path: '/c/$slug'
      fullPath: '/$lang/c/$slug'
      preLoaderRoute: typeof LangCSlugRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/p/$id': {
      id: '/$lang/p/$id'
      path: '/p/$id'
      fullPath: '/$lang/p/$id'
      preLoaderRoute: typeof LangPIdRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/page/$page': {
      id: '/$lang/page/$page'
      path: '/page/$page'
      fullPath: '/$lang/page/$page'
      preLoaderRoute: typeof LangPagePageRouteImport
      parentRoute: typeof LangRouteRoute
    }
  }
}

interface LangRouteRouteChildren {
  LangAdminRoute: typeof LangAdminRoute
  LangCategoriesRoute: typeof LangCategoriesRoute
  LangLoginRoute: typeof LangLoginRoute
  LangRankRoute: typeof LangRankRoute
  LangRegisterRoute: typeof LangRegisterRoute
  LangSavedRoute: typeof LangSavedRoute
  LangSearchRoute: typeof LangSearchRoute
  LangSubmitRoute: typeof LangSubmitRoute
  LangIndexRoute: typeof LangIndexRoute
  LangCSlugRoute: typeof LangCSlugRoute
  LangPIdRoute: typeof LangPIdRoute
  LangPagePageRoute: typeof LangPagePageRoute
}

const LangRouteRouteChildren: LangRouteRouteChildren = {
  LangAdminRoute: LangAdminRoute,
  LangCategoriesRoute: LangCategoriesRoute,
  LangLoginRoute: LangLoginRoute,
  LangRankRoute: LangRankRoute,
  LangRegisterRoute: LangRegisterRoute,
  LangSavedRoute: LangSavedRoute,
  LangSearchRoute: LangSearchRoute,
  LangSubmitRoute: LangSubmitRoute,
  LangIndexRoute: LangIndexRoute,
  LangCSlugRoute: LangCSlugRoute,
  LangPIdRoute: LangPIdRoute,
  LangPagePageRoute: LangPagePageRoute,
}

const LangRouteRouteWithChildren = LangRouteRoute._addFileChildren(
  LangRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRouteRoute: LangRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
